---
# Section 1.2: Systems of Linear Equations
---

### Linear systems

Given $A \in \mathbb{R}^{n \times n}$ and $b \in \mathbb{R}^n$, find $x \in \mathbb{R}^n$ such that:

$$
Ax = b.
$$

The linear system $Ax = b$ either:

1. has no solution;
2. has a unique solution;
3. has infinitely many solutions.

In fact, $Ax = b$ has a unique solution $x$ _if and only if_ $A$ is nonsingular (i.e., $A$ is invertible) (i.e., $\det(A) \ne 0$).

---

## Class discussion

Why does a linear system with multiple solutions necessarily have _infinitely many_ solutions?

Suppose $Ax = b$ has two solutions, $x_1$ and $x_2$. Then $A x_1 = b$ and $A x_2 = b$.

Let $x = (x_1 + x_2)/2$. Then $Ax = A((x_1 + x_2)/2) = (Ax_1 + Ax_2)/2 = (b + b)/2 =b$. Thus, $x$ is _another_ solution of $Ax = b$. 

Repeating this argument again and again, we conclude that $Ax = b$ has infinitely many solutions.

---

### Matrix inverse

If there is a matrix $B \in \mathbb{R}^{n \times n}$ such that

$$
AB = BA = I,
$$

where $I$ is the **identity matrix**, then we say that $B$ is the **inverse** of $A$, and we write

$$
B = A^{-1}.
$$

---

### Exercise:

Complete the following theorem.

> ### Theorem:
> Let $A \in \mathbb{R}^{n \times n}$. Then the following are equivalent:
>
> 1. $A^{-1}$ exists.
> 2. $A$ is row equivalent to the identity matrix.
> 3. $\det(A) \neq 0$.
> 4. The only solution to $Ax = 0$ is $x = 0$.
> 5. Rows and columns are linearly independent.
> 6. For every vector $b$, the linear system $Ax = b$ has a unique solution.
> 7. Dimension of $\{x : Ax = 0\}$ (the null space of $A$) is $0$.
> 8. $A$ is nonsingular.
> 9. $\text{rank}(A) = n$.

---

### Exercise:

Let $A$ be a nonsingular matrix. Multiply both sides of the linear system $Ax = b$ by $A^{-1}$ on the left. What do you conclude?

$$x = A^{-1}b$$

---

### Exercise:

Use the `inv` function in `Julia` to compute the inverse of a random matrix. Check that the computed inverse is correct.

In [17]:
using LinearAlgebra
A1 = rand(5, 5)
A2 = inv(A1)
A1*A2

5×5 Array{Float64,2}:
  1.0          -3.71575e-16   3.97673e-16   2.852e-17    1.07186e-16
  1.3188e-15    1.0          -1.5697e-16   -2.19151e-15  1.11383e-17
 -3.17126e-17   2.00446e-15   1.0          -1.79541e-15  2.84437e-16
  1.03926e-15   1.34138e-15  -1.07072e-15   1.0          2.25343e-16
 -4.08674e-16   2.58818e-16  -1.69983e-16  -4.80927e-16  1.0        

---

### Exercise:

In `Julia`, the linear system $Ax = b$ is solve using the "backslash" command: `\`.  This syntax is inherited from `MATLAB`.

Use the `\` function to compute the solution of a random linear system $Ax = b$.

In [18]:
n = 5
A = rand(n,n)
b = rand(n)
x = A\b

5-element Array{Float64,1}:
  0.5102009079369217
  1.7166951371167947
 -0.7100741125323806
 -1.0293528999345303
  1.073714498730199 

In [19]:
A*x - b

5-element Array{Float64,1}:
  2.220446049250313e-16
  0.0                  
 -5.551115123125783e-17
 -2.220446049250313e-16
 -2.220446049250313e-16

---

### Exercise:

Which is better, `x = A\b` or `x = inv(A)*b`?

In [13]:
using LinearAlgebra
n = 1000
A = rand(n,n)
b = rand(n)
x1 = A\b
x2 = inv(A)*b
println(norm(A * x1 - b))
println(norm(A * x2 - b))

6.270898346236246e-11
9.142754968285127e-11


In [15]:
n = 1000
A = rand(n,n)
x = ones(n) # or x = rand(n)
b = A*x
x1 = A\b
x2 = inv(A)*b
println(norm(x - x1))
println(norm(x - x2))

3.25000875267628e-11
4.100875215147093e-11


In [16]:
using BenchmarkTools
n = 1000
A = rand(n,n)
b = rand(n)
#b .= 0
@btime A\b
@btime inv(A)*b;

  21.302 ms (5 allocations: 7.65 MiB)
  60.694 ms (7 allocations: 8.13 MiB)


Summary:

1. `x = A\b` is faster (3x faster!)
2. `x = A\b` is more accurate (`norm(b - A*x)` is smaller)

---