---
# Section 3.2: Orthogonal Matrices
---

## Inner-product notation

We will use the following notation for the **inner-product** between vectors $x, y \in \mathbb{R}^n$:

$$
\langle x, y \rangle = \sum_{i=1}^n x_i y_i = x^T y = \|x\|_2 \|y\|_2 \cos\theta,
$$

where $0 \leq \theta \leq \pi$ is the **angle** between $x$ and $y$.

**Note:** $\|x\|_2 = \sqrt{\langle x, x \rangle}$.

---

## Orthogonal matrix definition

$Q \in \mathbb{R}^{n \times n}$ is **orthogonal** if the columns of $Q$ are:

1. **unit-length**: 
$$
\|q_i\|_2 = 1, \qquad \forall i,
$$
2. **mutually orthogonal**: 
$$
\langle q_i, q_j \rangle = 0, \qquad i \neq j
$$

This is equivalent to saying that

$$Q^T Q = I$$

which is equivalent to

$$Q^{-1} = Q^T.$$

The rows of $Q$ are also unit-length and mutually orthogonal since $QQ^T = I$.

---

## Exercise

1. Prove that the product of orthogonal matrices is orthogonal.

2. Prove that the transpose of an othogonal matrix is orthogonal.

---

> ## Theorem:

> If $Q \in \mathbb{R}^{n \times n}$ is orthogonal, then:

> 1. $\langle Qx, Qy \rangle = \langle x, y \rangle$

> 2. $\|Qx\|_2 = \|x\|_2$

This theorem states that any **orthogonal transformation**, $x \mapsto Qx$, preserve angles and lengths.

---

## Exercise:

Prove the theorem.

---

## Rotation matrices

A $2 \times 2$ rotation matrix has the form

$$
Q = \begin{bmatrix}
\cos\theta & -\sin\theta \\
\sin\theta & \cos\theta
\end{bmatrix}.
$$

We can use rotation matrices to introduce zeros into vectors.


---

## Exercise

1. Prove that rotation matrices are orthogonal.

2. Find a rotation matrix $Q$ such that
$$
Q^T \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} y_1 \\ 0 \end{bmatrix}
$$
where $y_1 \geq 0$.

In [ ]:
function rot(x1, x2)
    y1 = sqrt(x1^2 + x2^2)
    if y1 == 0.0
        c, s = 1.0, 0.0
    else
        c, s = x1/y1, x2/y1
    end
    return y1, c, s
end
        

In [ ]:
y1, c, s = rot(1.0, 1.0)

---

## $QR$-decomposition of a $2 \times 2$ matrix $A$

Suppose 

$$
A = \begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}.
$$

Let $Q$ be the rotation matrix that introduces a zero in the first column of $A$:
$$
Q^T \begin{bmatrix} a_{11} \\ a_{21} \end{bmatrix} = \begin{bmatrix} r_{11} \\ 0 \end{bmatrix}.
$$

Let
$$
\begin{bmatrix} r_{12} \\ r_{22} \end{bmatrix} = Q^T \begin{bmatrix} a_{21} \\ a_{22} \end{bmatrix}.
$$

Let
$$
R = \begin{bmatrix}
r_{11} & r_{12} \\
0 & r_{22}
\end{bmatrix}.
$$

Then $Q^T A = R$, and since $Q$ is orthogonal,

$$
A = QR.
$$

---

## Exercise

Compute the $QR$-decomposition of

$$
A = \begin{bmatrix}
1 & 2 \\
1 & 3
\end{bmatrix}.
$$

In [ ]:
A = [1 2; 1 3.0]

In [ ]:
Q, R = qr(A)

In [ ]:
Q*R - A

---

## Givens rotations

A **Givens rotation** matrix is

$$
Q = 
\begin{bmatrix}
1 \\
&\ddots\\
&&1\\
&&&c&&&&-s\\
&&&&1\\
&&&&&\ddots\\
&&&&&&1\\
&&&s&&&&c\\
&&&&&&&&1\\
&&&&&&&&&\ddots\\
&&&&&&&&&&1\\
\end{bmatrix},
$$

where $c = \cos\theta$ and $s = \sin\theta$. This matrix rotates the $(x_i,x_j)$ plane by an angle of $\theta$.

These matrices can be used to introduce zeros in general $n \times n$ matrices.

---

## Exercise

Use Givens rotations to compute the $QR$-decomposition of

$$
A = \begin{bmatrix}
1 & 2 & 0 \\
0 & 1 & 3 \\
1 & 3 & 0
\end{bmatrix}.
$$

In [4]:
A = [1 2 0; 0 1 3; 1 3 0.0]

Q, R = qr(A)

(
3x3 Array{Float64,2}:
 -0.707107   0.408248  -0.57735
  0.0       -0.816497  -0.57735
 -0.707107  -0.408248   0.57735,

3x3 Array{Float64,2}:
 -1.41421  -3.53553   0.0    
  0.0      -1.22474  -2.44949
  0.0       0.0      -1.73205)

In [5]:
R = [sqrt(2) 5/sqrt(2) 0; 0 sqrt(3/2) sqrt(6); 0 0 -sqrt(3)]

3x3 Array{Float64,2}:
 1.41421  3.53553   0.0    
 0.0      1.22474   2.44949
 0.0      0.0      -1.73205

In [6]:
Q = [sqrt(3) -1 -sqrt(2); 0 2 -sqrt(2); sqrt(3) 1 sqrt(2)]/sqrt(6)

3x3 Array{Float64,2}:
 0.707107  -0.408248  -0.57735
 0.0        0.816497  -0.57735
 0.707107   0.408248   0.57735

In [7]:
Q'*Q

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

---

## Solving $Ax = b$ using $QR$

If $Ax = b$ and $A = QR$, then

$$
Q(Rx) = b.
$$

If we let $c = Rx$, then we have $Qc = b$.

Thus, we have the following algorithm for solving $Ax = b$:

1. Let $c = Q^Tb$.
2. Solve $Rx = c$ using backward substitution.

---

## Exercise

Use the $QR$-decomposition of $A$ to solve $Ax = b$.

$$
A = \begin{bmatrix}
1 & 2 \\
1 & 3
\end{bmatrix},
\qquad
b = \begin{bmatrix} 1 \\ 2 \end{bmatrix}.
$$

In [11]:
A = [1 2; 1 3.0]
b = [1, 2.0]

Q, R = qr(A)

(
2x2 Array{Float64,2}:
 -0.707107  -0.707107
 -0.707107   0.707107,

2x2 Array{Float64,2}:
 -1.41421  -3.53553 
  0.0       0.707107)

In [12]:
c = Q'*b

2-element Array{Float64,1}:
 -2.12132 
  0.707107

In [13]:
x = R\c

2-element Array{Float64,1}:
 -1.0
  1.0

---

---

## Reflection matrices

Another way to create zeros in a matrix is by the [Householder reflection transformation](https://en.wikipedia.org/wiki/Householder_transformation):

$$
Q = I - 2uu^T, \qquad \|u\|_2 = 1.
$$

Let $L$ be the set of vectors $v$ that are orthogonal to the unit vector $u$,

$$
L = \left\{ v \in \mathbb{R}^n : u^T v = 0 \right\}.
$$

Then $L$ is a **hyperplane** containing the origin, and $Q$ reflects vectors $x$ across $L$.


---

## Properties of $Q = I - 2uu^T$

1. $Qu = -u$
2. If $v \in L$, then $Qv = v$.
3. $Q = Q^T$
4. $Q^TQ = I$
5. $Q^{-1} = Q$

---

## Exercise

Prove the above properties.

---

## Reflecting $x$ to $y$

If $\|u\|_2 \neq 1$, then the **Householder reflector** is

$$
Q = I - \gamma uu^T, \qquad \gamma = \frac{2}{\|u\|_2^2}.
$$

If $x, y \in \mathbb{R}^n$ such that $\|x\|_2 = \|y\|_2$, then the reflector $Q$ using 

$$u = x - y$$ 

satisfies

$$
Qx = y.
$$



---

## Creating zeros using reflectors

We want the reflector $Q$ that reflects $x$ to $y$, where

$$
x = 
\begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix},
\qquad
y = 
\begin{bmatrix} -\tau \\ 0 \\ \vdots \\ 0 \end{bmatrix},
\qquad
\tau = \mathrm{sign}(x_1)\|x\|_2.
$$

We define $u$ as

$$
u = \frac{x - y}{\tau + x_1} = 
\begin{bmatrix} 1 \\ x_2/(\tau + x_1) \\ \vdots \\ x_n/(\tau + x_1) \end{bmatrix}.
$$

Note that we have divided by $\tau + x_1$ to ensure that $u_1 = 1$.

Since $\tau$ and $x_1$ have the same sign, the calculation $\tau + x_1$ avoids catastrophic cancellation.

Letting 

$$
Q = I - \gamma uu^T, 
\qquad
\gamma = \frac{2}{\|u\|_2^2},
$$

we have

$$
Qx = \begin{bmatrix} -\tau \\ 0 \\ \vdots \\ 0 \end{bmatrix}.
$$



---

## Exercise

Prove that 
$$\gamma = \frac{\tau + x_1}{\tau}.$$

---

## `house`

We can now write a function to compute the $u$ and $\gamma$ of the Householder reflector $Q = I - \gamma uu^T$:

```julia
u, γ = house(x)
```

In [1]:
function house(x)
    u = copy(x)
    
    τ = norm(x)
    if τ == 0.0
        γ = 0.0
    else
        if x[1] < 0
            τ = -τ    # τ = sign(x[1])*norm(x)
        end
        γ = τ + x[1]  # γ temporarily stores τ + x[1]
        u[1] = 1.0    # u normalized to u[1] = 1
        u[2:end] /= γ # divide u[2:end] by τ + x[1]
        γ /= τ        # γ = (τ + x[1])/τ
    end
    
    return u, γ, τ
end

house (generic function with 1 method)

In [2]:
n = 5
x = randn(n)

u, γ, τ = house(x)

Q = eye(n) - γ*(u*u')

5x5 Array{Float64,2}:
 -0.601254  -0.350516    0.105653     0.105744     0.702344 
 -0.350516   0.923272    0.0231276    0.0231476    0.153744 
  0.105653   0.0231276   0.993029    -0.00697718  -0.0463418
  0.105744   0.0231476  -0.00697718   0.993017    -0.0463817
  0.702344   0.153744   -0.0463418   -0.0463817    0.691937 

In [3]:
issym(Q)

true

In [4]:
Q*Q

5x5 Array{Float64,2}:
  1.0           5.96484e-17  -1.16688e-17  -1.63856e-17  -1.5211e-16 
  5.96484e-17   1.0          -4.13021e-18   3.86013e-18  -1.65451e-17
 -1.16688e-17  -4.13021e-18   1.0          -1.46017e-19   2.92635e-17
 -1.63856e-17   3.86013e-18  -1.46017e-19   1.0           1.18559e-17
 -1.5211e-16   -1.65451e-17   2.92635e-17   1.18559e-17   1.0        

In [5]:
[x Q*x]

5x2 Array{Float64,2}:
  1.74148   -2.89641    
  1.01524   -2.77556e-16
 -0.306015   8.32667e-17
 -0.306279   1.11022e-16
 -2.03427    0.0        

In [6]:
norm(x)

2.8964055556620276

---

## `housetimes`

The way we computed $Qx$ in the above numerical example was inefficient. Note that

$$
Qx = \left(I - \gamma uu^T\right)x = x - \left[\gamma \left(u^T x\right)\right] u.
$$

In [7]:
housetimes(x::Vector, u, γ) = x - (γ*dot(u, x))*u

housetimes (generic function with 1 method)

In [8]:
n = 5
x = randn(n)

u, γ, τ = house(x)

housetimes(x, u, γ)

5-element Array{Float64,1}:
 -2.82245    
  0.0        
  1.11022e-16
 -2.22045e-16
  0.0        

---

## Exercise

Count the number of flops:
1. To form $Q$ and compute $Qx$.
2. To compute $x - \left[\gamma \left(u^T x\right)\right] u$.

** Solution: **

1. $3n^2 + 2n$ flops
2. $4n + 1$ flops

---

In the algorithm for computing the $QR$ decomposition of a matrix $A$, we will need to compute $QB$ where $B$ is a matrix.

$$
QB = B - (\gamma u) \left(u^TB\right)
$$

In [9]:
housetimes(B::Matrix, u, γ) = B - (γ*u)*(u'*B)

housetimes (generic function with 2 methods)

In [10]:
n = 5
B = rand(n,n)

u, γ, τ = house(B[:,1])

housetimes(B, u, γ)

5x5 Array{Float64,2}:
 -1.66785      -1.16103   -1.06713   -0.704652  -0.752904
  1.11022e-16   0.61231    0.18759    0.275494  -0.21571 
  1.11022e-16  -0.475375   0.180874   0.262555  -0.389677
  0.0          -0.079235  -0.383114  -0.34259   -0.224234
  0.0           0.215199  -0.467295  -0.369408   0.214215

---

## Exercise

Use Householder reflectors to numerically compute the $QR$-decomposition of

$$
A = \begin{bmatrix}
1 & 2 & 0 \\
0 & 1 & 3 \\
1 & 3 & 0
\end{bmatrix}.
$$

In [11]:
A = [1 2 0; 0 1 3; 1 3 0.0]
B = A

3x3 Array{Float64,2}:
 1.0  2.0  0.0
 0.0  1.0  3.0
 1.0  3.0  0.0

In [12]:
u, γ, τ = house(A[:,1])

([1.0,0.0,0.4142135623730951],1.7071067811865472,1.4142135623730951)

In [13]:
A = housetimes(A, u, γ)

3x3 Array{Float64,2}:
 -1.41421  -3.53553   0.0
  0.0       1.0       3.0
  0.0       0.707107  0.0

In [14]:
u, γ, τ = house(A[2:3,2])

([1.0,0.3178372451957822],1.816496580927726,1.224744871391589)

In [15]:
A[2:3,2:3] = housetimes(A[2:3,2:3], u, γ)

2x2 Array{Float64,2}:
 -1.22474  -2.44949
  0.0      -1.73205

In [16]:
A

3x3 Array{Float64,2}:
 -1.41421  -3.53553   0.0    
  0.0      -1.22474  -2.44949
  0.0       0.0      -1.73205

In [17]:
Q, R = qr(B)

(
3x3 Array{Float64,2}:
 -0.707107   0.408248  -0.57735
  0.0       -0.816497  -0.57735
 -0.707107  -0.408248   0.57735,

3x3 Array{Float64,2}:
 -1.41421  -3.53553   0.0    
  0.0      -1.22474  -2.44949
  0.0       0.0      -1.73205)

---

## The $QR$ Decomposition Algorithm

$$A_0 = A$$

$$
A_1 = Q_1A = 
\left[\begin{array}{c|c}
-\tau_1 & a_1^T \\ \hline
0 & \hat{A}_1
\end{array}\right],
\qquad
Q_1 = I_n - \gamma_1 u_1 u_1^T
$$

$$
A_2 = Q_2Q_1A = 
\left[\begin{array}{c|c}
-\tau_1 & a_1^T \\ \hline
0 &
\begin{array}{c|c}
-\tau_2 & a_2^T \\ \hline
0 & \hat{A}_2
\end{array}
\end{array}\right],
\qquad
Q_2 = 
\left[\begin{array}{c|c}
1 & \\\hline
& I_{n-1} - \gamma_2 u_2 u_2^T
\end{array}\right]
$$

$$
A_3 = Q_3Q_2Q_1A = 
\left[\begin{array}{c|c}
-\tau_1 & a_1^T \\ \hline
0 &
\begin{array}{c|c}
-\tau_2 & a_2^T \\ \hline
0 & 
\begin{array}{c|c}
-\tau_3 & a_3^T \\ \hline
0 & \hat{A}_3
\end{array}
\end{array}
\end{array}\right],
\qquad
Q_3 = 
\left[\begin{array}{c|c}
I_2 & \\\hline
& I_{n-2} - \gamma_3 u_3 u_3^T
\end{array}\right]
$$

$$\vdots$$

$$
A_{n-1} = Q_{n-1} \cdots Q_1A = 
\left[\begin{array}{c|c}
-\tau_1 & a_1^T \\ \hline
0 &
\begin{array}{c|c}
-\tau_2 & a_2^T \\ \hline
0 & 
\begin{array}{c|c}
-\tau_3 & a_3^T \\ \hline
0 & 
\begin{array}{c|c}
\ddots & \ddots \\ \hline
0 & 
\begin{array}{c|c}
-\tau_{n-1} & a_{n-1}^T \\ \hline
0& \hat{A}_{n-1}
\end{array}
\end{array}
\end{array}
\end{array}
\end{array}\right] = R
$$

We then let $Q = Q_1Q_2 \cdots Q_{n-1}$ and obtain $A = QR$.

---

## Storing $u_i$'s and $\gamma_i$'s

Each $u_i$ is normalized so that

$$
u_i = \begin{bmatrix} 1\\*\\\vdots\\* \end{bmatrix}.
$$

Thus we do not need to store the first entry since it is always $1$.

The rest of the entries of $u_i$ can be stored where the zeros are created.

To store the $\gamma_i$'s, we create a separate vector

$$
\gamma = \begin{bmatrix} \gamma_1\\\vdots\\\gamma_{n-1} \end{bmatrix}.
$$

---

## `myqr`

In [18]:
immutable myQRfactorization
    V::Matrix{Float64}
    γ::Vector{Float64}
end

function myqr(A::Matrix{Float64})
    m, n = size(A)
    
    m == n || error("This QR decomposition algorithm requires a square input matrix.")
        
    V = copy(A)
    γ = zeros(n-1)
    for k = 1:n-1
        u, γ[k], τ = house(V[k:n,k])  # compute the Householder reflector I - γuu'
        V[k,k] = -τ                   # diagonal entries become -τ
        V[k+1:n,k] = u[2:end]         # store u's in lower-triangular part of V
        V[k:n,k+1:n] -= (γ[k]*u)*(u'*V[k:n,k+1:n]) # housetimes
    end
    
    myQRfactorization(V, γ)
end

myqr (generic function with 1 method)

In [19]:
n = 5
A = rand(n, n)

myF = myqr(A)

myQRfactorization(5x5 Array{Float64,2}:
 -1.21171   -0.646615  -1.02701   -0.568412  -0.905701 
  0.359355   0.596753   0.311726   0.342726   0.28903  
  0.323829  -0.341619  -0.325343  -0.108412  -0.659205 
  0.541513   0.34095   -0.712624   0.565056   0.732905 
  0.400704   0.313635  -0.145891   0.245047   0.0650549,[1.1849735384164892,1.5022709510812486,1.3079440004593315,1.8867072414100412])

In [20]:
Q, R = qr(A)

(
5x5 Array{Float64,2}:
 -0.184974   0.569336  -0.0900274   0.786494    0.122327
 -0.425826  -0.297677  -0.757704    0.0884645  -0.384863
 -0.383729   0.697573  -0.0893032  -0.593676   -0.075621
 -0.641679  -0.203897   0.636013    0.124823   -0.355783
 -0.474824  -0.243029  -0.0727532  -0.0746314   0.839414,

5x5 Array{Float64,2}:
 -1.21171  -0.646615  -1.02701   -0.568412  -0.905701 
  0.0       0.596753   0.311726   0.342726   0.28903  
  0.0       0.0       -0.325343  -0.108412  -0.659205 
  0.0       0.0        0.0        0.565056   0.732905 
  0.0       0.0        0.0        0.0        0.0650549)

In [21]:
UpperTriangular(myF.V)

5x5 UpperTriangular{Float64,Array{Float64,2}}:
 -1.21171  -0.646615  -1.02701   -0.568412  -0.905701 
  0.0       0.596753   0.311726   0.342726   0.28903  
  0.0       0.0       -0.325343  -0.108412  -0.659205 
  0.0       0.0        0.0        0.565056   0.732905 
  0.0       0.0        0.0        0.0        0.0650549

---

## Flop count of $QR$ Decomposition Algorithm

In each iteration, we need to compute `housetimes`:

1. $\left(I_n - \gamma_1 u_1 u_1^T\right) A_{0}[1:n,\ 2:n]$

2. $\left(I_{n-1} - \gamma_2 u_2 u_2^T\right) A_{1}[2:n,\ 3:n]$

3. $\left(I_{n-2} - \gamma_3 u_3 u_3^T\right) A_{2}[3:n,\ 4:n]$

$\vdots$

In iteration $k$, we compute

$$
\left(I_{n-k+1} - \gamma_k u_k u_k^T\right) A_{k-1}[k:n,\ k+1:n].
$$

This operation requires approximately $4(n - k + 1)^2$ flops if done efficiently.

We also need to compute $\gamma_k$ and $u_k$ from $A_{k-1}[k:n, k]$, but this is only $O(n)$.

Therefore, the $QR$ Decomposition Algorithm requires

$$
\sum_{k=1}^{n-1} 4(n-k+1)^2 \approx \int_1^{n-1} 4(n-x+1)^2 dx = \frac{4}{3}n^3.
$$

This does not include forming $Q$ though.

---

## Forming $Q$

We can use the $u_i$'s and the $\gamma_i$'s to compute

$$QB = Q_1Q_2\cdots Q_{n-1} B$$

$$Q^T B = Q_{n-1}\cdots Q_2 Q_1 B$$

efficiently without forming $Q$.


We can form $Q$ by computing $QI_n$:

$$
\begin{align}
Q = QI_n &= Q_1 Q_2\cdots Q_{n-1} I_n\\
&= 
\left[\begin{array}{c}
I_{n} - \gamma_1 u_1 u_1^T
\end{array}\right]
\left[\begin{array}{c|c}
I_1 & \\\hline
& I_{n-1} - \gamma_2 u_2 u_2^T
\end{array}\right]
\cdots
\left[\begin{array}{c|c}
I_{n-2} & \\\hline
& I_{2} - \gamma_{n-1} u_{n-1} u_{n-1}^T
\end{array}\right] I_n
\end{align}
$$

Done efficiently (from right to left), this calculation requires an additional $\frac43n^3$ flops.

---

## `Qtimes` and `formQ`

In [22]:
function Qtimes!(F::myQRfactorization, B::Matrix; T=false)
    n = size(F.V, 1)
    cols = T ? (1:n-1) : (n-1:-1:1)
    for k = cols
        γk = F.γ[k]
        uk = [1.0; F.V[k+1:n,k]]
        B[k:n,k:n] -= (γk*uk)*(uk'*B[k:n,k:n])
    end
    B
end
Qtimes(F::myQRfactorization, B::Matrix) = Qtimes!(F, copy(B))

QTtimes!(F::myQRfactorization, B::Matrix) = Qtimes!(F, B, T=true)
QTtimes(F::myQRfactorization, B::Matrix) = Qtimes!(F, copy(B), T=true)

formQ(F::myQRfactorization) = Qtimes(F, eye(size(F.V,1)))

formQ (generic function with 1 method)

In [23]:
n = 5
A = rand(n, n)
F = myqr(A)

Q = formQ(F)

5x5 Array{Float64,2}:
 -0.490761    0.298856   -0.254541  -0.770368    0.107616 
 -0.448226   -0.113792    0.750086  -0.071722   -0.467303 
 -0.726151    0.0467691  -0.328601   0.598504    0.0658095
 -0.0713743  -0.84172    -0.385206  -0.197729   -0.314535 
 -0.160802   -0.4325      0.340907  -0.0639162   0.816568 

In [24]:
Q'*A

5x5 Array{Float64,2}:
 -1.33032      -1.13743      -0.795223     -0.925098     -0.652679
  7.29443e-18  -0.886931     -0.364557     -0.554664     -1.11912 
 -6.31425e-17   1.90005e-16   0.781381     -0.301029      0.32143 
 -6.52433e-17  -4.28582e-18   1.08256e-17  -0.617856     -0.34784 
  7.04383e-17  -6.97146e-18   5.28094e-17   5.42512e-17  -0.182478

In [25]:
QTtimes(F, A)

5x5 Array{Float64,2}:
 -1.33032      -1.13743      -0.795223     -0.925098  -0.652679
 -1.11022e-16  -0.886931     -0.364557     -0.554664  -1.11912 
 -1.11022e-16   0.0           0.781381     -0.301029   0.32143 
 -2.77556e-17  -1.11022e-16  -1.11022e-16  -0.617856  -0.34784 
 -2.77556e-17   0.0           0.0           0.0       -0.182478

---

## Flop count summary

Let $A \in \mathbb{R}^{n \times n}$.

`chol(A)`: $\frac13n^3$

`lu(A)`:  $\frac23n^3$

`qrfact(A)` does not form $Q$: $\frac43n^3$

`qr(A)` forms $Q$: $\frac83n^3$


---

## Flop count to solve $Ax = b$ by $QR$

**Algorithm:**

1. Compute the $QR$ Decomposition of $A$, but do not form $Q$.
2. $c = Q^Tb$
3. Use backward substitution to solve $Rx = c$

The cost of the $QR$ Decomposition is $\frac43n^3$.

The cost of computing $c = Q^Tb$ efficiently (using the $u_i$'s and the $\gamma_i$'s) is about $2n^2$ flops.

Backward substitution is $n^2$ flops.

Therefore, in total we have 
$$\frac43n^3 + O(n^2)$$ 
flops to solve $Ax = b$ by $QR$.

---

## `x = F\b`

In [26]:
function Qtimes!(F::myQRfactorization, b::Vector; T=false)
    n = size(F.V, 1)
    cols = T ? (1:n-1) : (n-1:-1:1)
    for k = cols
        γk = F.γ[k]
        uk = [1.0; F.V[k+1:n,k]]
        b[k:n] -= (γk*uk)*dot(uk, b[k:n])
    end
    b
end
Qtimes(F::myQRfactorization, b::Vector) = Qtimes!(F, copy(b))

QTtimes!(F::myQRfactorization, b::Vector) = Qtimes!(F, b, T=true)
QTtimes(F::myQRfactorization, b::Vector) = QTtimes!(F, copy(b))

QTtimes (generic function with 2 methods)

In [27]:
n = 5
A = rand(n, n)
b = rand(n)

F = myqr(A)

c = QTtimes(F, b)

5-element Array{Float64,1}:
 -0.94807 
 -0.275826
 -0.182984
  0.32698 
  0.179401

In [28]:
R = UpperTriangular(F.V)

5x5 UpperTriangular{Float64,Array{Float64,2}}:
 -1.56403  -0.594123  -0.767496  -1.16111   -0.956755
  0.0      -0.843687  -0.866259  -0.555781  -0.520591
  0.0       0.0        0.626959  -0.211049  -0.299551
  0.0       0.0        0.0       -0.451143  -0.106553
  0.0       0.0        0.0        0.0       -0.298074

In [29]:
x = R\c

5-element Array{Float64,1}:
  1.07391 
  1.87841 
 -0.775547
 -0.582627
 -0.601868

In [30]:
b - A*x

5-element Array{Float64,1}:
  4.44089e-16
 -4.44089e-16
 -5.55112e-17
  2.22045e-16
 -1.38778e-16

In [31]:
b - A*(A\b)

5-element Array{Float64,1}:
 -2.22045e-16
  3.33067e-16
  0.0        
 -1.11022e-16
  1.38778e-16

---

In [32]:
import Base.\

\(F::myQRfactorization, b::Vector) = UpperTriangular(F.V)\QTtimes(F, b)

\ (generic function with 61 methods)

In [33]:
x = F\b

5-element Array{Float64,1}:
  1.07391 
  1.87841 
 -0.775547
 -0.582627
 -0.601868

In [34]:
b - A*x

5-element Array{Float64,1}:
  4.44089e-16
 -4.44089e-16
 -5.55112e-17
  2.22045e-16
 -1.38778e-16

---

> ## $QR$ Decomposition Theorem

> Let $A \in \mathbb{R}^{n \times n}$. Then the following hold.

> 1. There exists $Q, R \in \mathbb{R}^{n \times n}$ such that $Q$ is orthogonal, $R$ is upper-triangular, and $A = QR$.

> 2. If $A$ is **nonsingular**, then $\exists$ **unique** $Q, R \in \mathbb{R}^{n \times n}$ such that $Q$ is orthogonal, $R$ is upper-triangular with **positive diagonal entries**, and $A = QR$.

### Proof.

1. Hint: Use Householder reflectors and induction on $n$.
2. Hint: Let $D$ be diagonal with $d_{ii} = \mathrm{sign}(r_{ii})$.

---

## Stability

Multiplication by rotators or reflectors is stable:

$$
\mathrm{fl}(QA) = Q(A + E)
$$

where $\frac{\|E\|_2}{\|A\|_2}$ is tiny.

Also,

$$
\mathrm{fl}(Q_2Q_1A) = Q_2Q_1(A + E),
$$

where $\|E\|_2 = \left\|E_1 + Q_1^T E_2\right\|_2 \leq \|E_1\|_2 + \left\|Q_1^TE_2\right\|_2 = \|E_1\|_2 + \left\|E_2\right\|_2$. Therefore, $\frac{\|E\|_2}{\|A\|_2}$ is tiny.

---